name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: {{ secrets.GITHUB_TOKEN }}
          branch: main