name: CI

on:
  push:
    paths: [ ./SCSS/Spectrum.scss ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source Git branch
          uses: actions/checkout@v2
        - run: |
            yarn
            yarn build
            git add .
            git push --amend --no-edit